[tool.flet.android]
dependencies = ['flet','certifi','pyyaml','flet-lottie','flet-audio']

[project]
name = "LUDO CLASH"
version = "1.0.0"
description = "Luck is on your side."
authors = [
  {name = "Yogya Chugh", email = "yogya.developer@gmail.com"}
]